Move things around hoping they'll fix a misterious CI error
For some reason the mongo database fails to authenticate the lms daemon.

  File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 213, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command SON([('saslStart', 1), ('mechanism', 'SCRAM-SHA-1'), ('autoAuthorize', 1), ('payload', Binary(b'n,,n=edxapp,r=NjY5MTI4NzA2OTY2MzQ5', 0))]) on namespace complete_mongoedx.$cmd failed: Authentication failed.

Also, the CMS daemon can't find the MySQL tables it expects:

  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'dark_lang_darklangconfig.enable_beta_languages' in 'field list'")